/*import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

*/




/*'use client';

import { GlobalStyle } from "@/styles/globals";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalStyle />
        {children}
      </body>
    </html>
  );
}
*/

/*'use client';

import { GlobalStyle } from "@/styles/globals";
import { useThemeToggle } from "@/context/ThemeContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isDark } = useThemeToggle(); // agora você tem acesso ao estado do tema

  return (
    <html lang="en">
      <body>
        
        <GlobalStyle />
        {children}
      </body>
    </html>
  );
}

*/

"use client";

import { ThemeContextProvider } from "@/context/ThemeContext";
import { GlobalStyle } from "@/styles/globals";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <ThemeContextProvider>
          <GlobalStyle />
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}

